In [1]:
!pip install faker

import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()
np.random.seed(42)
print("Libraries loaded successfully")

Collecting faker
  Downloading faker-37.12.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: tzdata in /Users/imamuddin/venv-metal/lib/python3.9/site-packages (from faker) (2025.2)
Downloading faker-37.12.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 13.5 MB/s  0:00:00 eta 0:00:01
Installing collected packages: faker
Successfully installed faker-37.12.0

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Libraries loaded successfully

Defining Parameters

In [2]:
NUM_CUSTOMERS = 50

INDUSTRIES = [
    'Electric Utility',
    'Gas Utility', 
    'Water Utility',
    'Telecom',
    'Railways'
]

print(f"Generating data for {NUM_CUSTOMERS} customers")
print(f"Industries: {INDUSTRIES}")

Generating data for 50 customers
Industries: ['Electric Utility', 'Gas Utility', 'Water Utility', 'Telecom', 'Railways']

Generating Each column

In [3]:
customer_ids = [f'C{str(i).zfill(3)}' for i in range(1, NUM_CUSTOMERS + 1)]

customer_names = [fake.company() for _ in range(NUM_CUSTOMERS)]

industries = np.random.choice(INDUSTRIES, size=NUM_CUSTOMERS)

contract_values = np.random.choice(
    [50000, 75000, 100000, 150000, 200000],
    size=NUM_CUSTOMERS
)

logins_last_30_days = np.random.randint(0, 30, size=NUM_CUSTOMERS)

feature_adoption_rate = np.round(
    np.random.uniform(0.1, 1.0, size=NUM_CUSTOMERS), 2
)

open_tickets = np.random.randint(0, 10, size=NUM_CUSTOMERS)

days_since_last_login = np.random.randint(1, 60, size=NUM_CUSTOMERS)

contract_renewal_days = np.random.randint(10, 365, size=NUM_CUSTOMERS)

ai_acceptance_rate = np.round(
    np.random.uniform(0.2, 1.0, size=NUM_CUSTOMERS), 2
)

print("All columns generated successfully")

All columns generated successfully

Assemble Dataframe

In [4]:
df = pd.DataFrame({
    'customer_id'           : customer_ids,
    'customer_name'         : customer_names,
    'industry'              : industries,
    'contract_value'        : contract_values,
    'logins_last_30_days'   : logins_last_30_days,
    'feature_adoption_rate' : feature_adoption_rate,
    'open_tickets'          : open_tickets,
    'days_since_last_login' : days_since_last_login,
    'contract_renewal_days' : contract_renewal_days,
    'ai_acceptance_rate'    : ai_acceptance_rate
})

print(f"Dataframe shape: {df.shape}")
df.head(10)

Dataframe shape: (50, 10)

,customer_id,customer_name,industry,contract_value,logins_last_30_days,feature_adoption_rate,open_tickets,days_since_last_login,contract_renewal_days,ai_acceptance_rate
0,C001,Livingston-Yates,Telecom,150000,27,0.59,6,48,31,0.66
1,C002,"Reid, Rice and Reyes",Railways,150000,6,0.28,7,16,247,0.28
2,C003,Blevins-Peterson,Water Utility,150000,8,0.95,0,3,167,0.69
3,C004,Mays Group,Railways,200000,7,0.64,5,20,47,0.99
4,C005,Vazquez-Lopez,Railways,100000,11,0.73,7,24,239,0.31
5,C006,"Price, King and Simpson",Gas Utility,50000,1,0.89,4,54,60,0.61
6,C007,Woods Inc,Water Utility,150000,0,0.66,3,56,273,0.90
7,C008,Garcia-Lee,Water Utility,75000,15,0.37,1,33,292,0.79
8,C009,Wood-Hoffman,Water Utility,150000,22,0.19,5,24,36,0.76
9,C010,Perry Group,Railways,75000,22,0.51,5,52,235,0.76

Performing EDA

In [6]:
df.describe()

,contract_value,logins_last_30_days,feature_adoption_rate,open_tickets,days_since_last_login,contract_renewal_days,ai_acceptance_rate
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.00000
mean,114500.000000,12.940000,0.504200,4.300000,29.680000,176.920000,0.61660
std,54653.360335,9.283318,0.236653,2.901442,16.548556,105.878606,0.22321
min,50000.000000,0.000000,0.100000,0.000000,2.000000,13.000000,0.22000
25%,75000.000000,4.500000,0.322500,2.000000,17.250000,64.000000,0.46250
50%,100000.000000,12.000000,0.470000,4.000000,31.000000,185.500000,0.63000
75%,150000.000000,22.000000,0.667500,7.000000,44.750000,271.000000,0.78750
max,200000.000000,29.000000,1.000000,9.000000,59.000000,358.000000,0.99000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            50 non-null     object
 1   customer_name          50 non-null     object
 2   industry               50 non-null     object
 3   contract_value         50 non-null     int64
 4   logins_last_30_days    50 non-null     int64
 5   feature_adoption_rate  50 non-null     float64
 6   open_tickets           50 non-null     int64
 7   days_since_last_login  50 non-null     int64
 8   contract_renewal_days  50 non-null     int64
 9   ai_acceptance_rate     50 non-null     float64
dtypes: float64(2), int64(5), object(3)
memory usage: 4.0+ KB